### ISSUE TITLE
User can take a quiz to identify Pokemon

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#1]
## 💰 Motivation

Users will want to test their knowledge for various Pokemon while being timed.

## 📐 Plan

Create a timed minigame where the user matches an answer to the silhouette of a pokemon

## 🖼️ Wireframes

![user can create an entry mobile](https://i.gyazo.com/5167890ce8970d40dacab638b46b7745.png)
![user can create an entry desktop](https://i.gyazo.com/d359f5b34de8b0c5f9ce86cc7d68f2cb.png)

## ✅ Task List

- [x] Add a `div[data-view="home"]` to the HTML.
- [x] Create a home screen looks good on both mobile and desktop screens
- [x] Add an event listener on first homepage button start the quiz
- [x] Create a modal where user can input their name
- [x] Add modal buttons to submit or cancel.
- [x] User can start quiz once they input their name and data-view switches from home to quiz
- [x] Create a DOM Tree upon starting the quiz.
- [x] Create a data object that accounts for user name
- [x] Update data object on which question number they are on.
- [x] Update the h1 textContent related to current question number in data object.
- [x] Include a progress bar for each question on the quiz
- [x] Include a 10 second css animation timer
- [x] Animate the timer to last 10 seconds.
- [x] Wait for image to load then prepend progress bar and append quiz questions.
- [x] Include a 10 second setInterval as quiz elements loads
- [x] Create a quiz every time a user selects a quiz option.
- [x] Change the dots to pokeballs if it is a correct answer
- [x] Clear setInterval everytime a quiz DOM appears and recreate setInterval.
- [x] After currentQuestionNumber reaches 10, the next function doesn't create a new quiz DOM question.
