### ISSUE TITLE
Feature: User can delete an old score

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#15]
## 💰 Motivation

User can now view instructions and delete an old score

## 📐 Plan

User has access to their old scores upon clicking it in the home page. User will be able to click the icon next to their name to delete that score.

## 🖼️ Wireframes

![image](https://i.gyazo.com/2eddc73be96bc191d2892029454b8d7d.png)

## ✅ Task List

- [x] Create a new modal for instructions with information on how to play
- [x] Add a new button to the home page labeled 'How to play'
- [x] Add an event listener to that button to change the className for the modal from hidden to not hidden
- [x] Add another button inside of the modal
  - [x] Add a click event for the button that gives the modal a className of hidden
- [x]  Inside our loop for creating each trainer entry of pastGames, add an icon to on the same line of the trainerName inside of the trainerEntry function
  - [x] Add a click event to each trash icon to delete that entry
