### ISSUE TITLE
Feature: User can change difficulties

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#16]
## 💰 Motivation

User can switch their difficulty to hard mode

## 📐 Plan

User can click on the pokeball logo on the homepage to change difficulties. Clicking it once more returns it make to default.

## 🖼️ Wireframes

![image](https://i.gyazo.com/126356cbaae3e0e03c98f24e685aff66.png)

## ✅ Task List

- [x] Query the DOM for the logo id.
- [x] Add a click event handler to the logo that changes its attribute `src` to masterball.png
- [x] Create a new property in our data object called hardMode with the value of false.
- [x] Create an if statement during the click event checking with the property value of `data.hardMode` is.
  - [x] If it is false, set hardMode to true, and change the img src to masterball. Else, set hardMode to false, and set img src to pokeball.png
- [x]  Inside our `quizQuestion` function, when our http request is getting the image, set the class to `.silhouette`. 
- [x] Create a new class called .`silhouette` that sets filter:brightness to 0 and make it so users can't ghost drag the quiz image.
