### ISSUE TITLE
Feature: User can check pokedex entry on pokemon from past quizzes

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#18]
## 💰 Motivation

User can check pokedex entry on pokemon from past quizzes

## 📐 Plan

User can click on pokemon sprites within the past history games container, sending them to the pokedex with the name automatically searched.

## 🖼️ Wireframes

![image](https://i.gyazo.com/41d8975733b9b3a1fab4bfd50dd28aa3.png)

## ✅ Task List

- [x] During the createTrainerEntry function, add an attribute named pokemon-name with the related name to every sprite created
- [x] Add a click event handler to every pokemon sprite
  - [x] Create a function that switches the data-view to pokedex
  - [x] Change the pokedex input to the sprites attribute value
  - [x] Run the function that appends the picture to the pokedex screen based on the input value
- [x] Make it so everytime pokedex data-view changes to homepage, remove the current pokedex entry displayed
- [x] Double check that all elements are removed if user searches for another entry.
- [x] Remove all console logs
- [x] Double check variable names are related to what their function is.
