### ISSUE TITLE
User can save their scores

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#2]
## 💰 Motivation

Once a user starts the game, their name gets saved into the data object. When a user completes the game, that user object is now saved into localStorage.

## 📐 Plan

Account for username input as the quiz starts. When the user selects "retry" or "return to menu", the name, correct pokemon guesses and wrong pokemon guesses are placed into an object in the `data.pastHistory` array

## 🖼️ Wireframes

![user can view their entries mobile](https://i.gyazo.com/ec69e9a74b6af47cca93a25d9d342f3f.png)
![user can view their entries desktop](https://i.gyazo.com/36e03f8b7d1482a98e3e60bf237c95b9.png)

## ✅ Task List

- [x] User must input a name.
- [x] Input value gets saved into the data object
- [x] Include last question in total score
- [x] Data object has a value for current quiz question
- [x] Quiz stops when the data object runs the quiz at after 10 questions
- [x] Modal appears by removing class `.hidden`
  - [x] Modal has the option to go back to menu or to replay the game
    - [x] Menu button resets form values to default 
    - [x] Replay the game resets form values to default and calls functions to play quiz.
- [x] Either modal choice saves the correct and wrong pokemon and player name into an object, then resets it.
