### ISSUE TITLE
User can view their past scores

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#3]
## 💰 Motivation

User can now view old scores by clicking Play History button on the home screen.

## 📐 Plan

Generate a DOM tree for each past game which is in the data.pastGames array.

## 🖼️ Wireframes

![user can view their entries mobile](https://i.gyazo.com/a0c50002dacee1b94e82511ef832aae5.png)
![user can view their entries desktop](![image](https://i.gyazo.com/55e034928b3940ce06051512b405f7fb.png)

## ✅ Task List

- [x] Add an event listener on the home page button, "Play History", for clicks
  - [x] Clicking the button switches to `div[data-view="playHistory"]`
- [x] On click, generate DOM trees for each object in the pastGames array
- [x] Create a new container to encapsulate whole trainer data
  - [x] Include the trainers Name at the top
  - [x] Have a row for correctPokemon
  - [x] Have a row for incorrectPokemon
 - [x] Loop through the pastGames array and recreate the DOM Tree
