### ISSUE TITLE
User can replay quiz

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#4]
## 💰 Motivation

User can now click replay the game instead of only being able to exit to home screen.

## 📐 Plan

User clicking replay the game resets all data properties except for username. Generate 4 new pokemon, and use the createQuiz function

## 🖼️ Wireframes

![user can view the replay button on  desktop](![image](![image](https://i.gyazo.com/6934c0d1e5919fde5bc4e69cfe114b8a.png)

## ✅ Task List

- [x] Create a button on the end quiz modal screen
- [x] Add textContent retry onto the replay button
- [x]  Add an event listener to the replay button for clicks
  - [x] On click, reset the data object except for data.trainername
- [x] Resetting the game also resets the header above to the current question #
