### ISSUE TITLE
User can view details of a pokemon

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/whos-that-pokemon#5]
## 💰 Motivation

User can now view the Pokedex and search their entries

## 📐 Plan

User has access to the Pokedex data-view upon clicking it in the home page. The background of the pokedex page will resemble a pokedex and they can input a pokemon name. Upon submit, a network request will get the specified pokemon's sprite, type, and base stats.

## 🖼️ Wireframes

![image](https://i.gyazo.com/646746832419feb371d49c47ed3c86d1.png)

## ✅ Task List

- [x] Create a new button on the home page titled "Pokedex"
- [x] Add an event listener for click on the Pokedex Button
  - [x] Event handler switches to `div[data-view="pokedex"]`
  - [x] $h1 at the top left changes from "Who's that Pokemon" to "Pokedex"
  - [x] $body color changes to red
- [x] Create an input for users to input the pokemon name they want
- [x] Create a submit button which listens to the input value.
- [x] Add an event handler for click on pokedex submit button.
  - [x] A user click, will do a network request for the searched image, stats, type.
  - [x] Create a DOM Tree to be appended within the .screen div. 
    - [x] Have 2 columns (50% width) and rows between each.
  - [x] Also, should remove any pre-existing nodes before just in-case the user wants to search again.
